### ISSUE TITLE
portions of Bulugh al-Maram missing

### ISSUE THREAD

**Issue by ni-mo** [QuranX/QuranX#28]
hi, 

Looking at Bulugh al-Maram Hadith: 

https://raw.githubusercontent.com/QuranX/QuranX/master/src/QuranX.DataMigration/App_Data/Hadiths/Maram.xml

Seems a bunch of the text is missing, e.g. book 2, book 7, book 8. 

Compare with: 

https://sunnah.com/bulugh

Thanks....

**Comment by QuranX** [comment]
We are updating QuranX.com now.  Thank you for letting us know this was missing!

**Comment by ni-mo** [comment]
Hi, 

 

Question: 

 

On quranx.com this hadith: https://quranx.com/hadith/Nasai/DarusSalam/Volume-3/Book-21/Hadith-2039/ translates Aishah saying: “I said, 'Yes.' He struck me on the chest which caused me pain,”, however, in the XML files on github (https://github.com/QuranX/QuranX/blob/master/src/QuranX.DataMigration/App_Data/Hadiths/Nasai.xml), it’s translated as: “, “He gave me a nudge on the chest which I felt”: 

 

<hadith>

      <references>

        <reference>

          <code>DarusSalam</code>

          <suffix />

          <parts>

            <part>3</part>

            <part>21</part>

            <part>2039</part>

          </parts>

        </reference>

        <reference>

          <code>In-Book</code>

          <suffix />

          <parts>

            <part>21</part>

            <part>221</part>

          </parts>

        </reference>

        <reference>

          <code>Reference</code>

          <suffix />

          <parts>

            <part>2037</part>

          </parts>

        </reference>

      </references>

      <arabic>

        <text>أَخْبَرَنَا يُوسُفُ بْنُ سَعِيدٍ، قَالَ حَدَّثَنَا حَجَّاجٌ، عَنِ ابْنِ جُرَيْجٍ، قَالَ أَخْبَرَنِي عَبْدُ اللَّهِ بْنُ أَبِي مُلَيْكَةَ، أَنَّهُ سَمِعَ مُحَمَّدَ بْنَ قَيْسِ بْنِ مَخْرَمَةَ، يَقُولُ سَمِعْتُ عَائِشَةَ، تُحَدِّثُ قَالَتْ ‏:‏ أَلاَ أُحَدِّثُكُمْ عَنِّي وَعَنِ النَّبِيِّ صلى الله عليه وسلم قُلْنَا ‏:‏ بَلَى ‏.‏ قَالَتْ ‏:‏ لَمَّا كَانَتْ لَيْلَتِي الَّتِي هُوَ عِنْدِي تَعْنِي النَّبِيَّ صلى الله عليه وسلم انْقَلَبَ فَوَضَعَ نَعْلَيْهِ عِنْدَ رِجْلَيْهِ، وَبَسَطَ طَرَفَ إِزَارِهِ عَلَى فِرَاشِهِ، فَلَمْ يَلْبَثْ إِلاَّ رَيْثَمَا ظَنَّ أَنِّي قَدْ رَقَدْتُ، ثُمَّ انْتَعَلَ رُوَيْدًا وَأَخَذَ رِدَاءَهُ رُوَيْدًا، ثُمَّ فَتَحَ الْبَابَ رُوَيْدًا وَخَرَجَ رُوَيْدًا وَجَعَلْتُ دِرْعِي فِي رَأْسِي وَاخْتَمَرْتُ وَتَقَنَّعْتُ إِزَارِي، وَانْطَلَقْتُ فِي إِثْرِهِ حَتَّى جَاءَ الْبَقِيعَ، فَرَفَعَ يَدَيْهِ ثَلاَثَ مَرَّاتٍ فَأَطَالَ، ثُمَّ انْحَرَفَ فَانْحَرَفْتُ، فَأَسْرَعَ فَأَسْرَعْتُ، فَهَرْوَلَ فَهَرْوَلْتُ، فَأَحْضَرَ فَأَحْضَرْتُ وَسَبَقْتُهُ فَدَخَلْتُ، فَلَيْسَ إِلاَّ أَنِ اضْطَجَعْتُ فَدَخَلَ فَقَالَ ‏:‏ ‏"‏ مَا لَكِ يَا عَائِشَةُ حَشْيَا رَابِيَةً ‏"‏ ‏.‏ قَالَتْ ‏:‏ لاَ ‏.‏ قَالَ ‏:‏ ‏"‏ لَتُخْبِرِنِّي أَوْ لَيُخْبِرَنِّي اللَّطِيفُ الْخَبِيرُ ‏"‏ ‏.‏ قُلْتُ ‏:‏ يَا رَسُولَ اللَّهِ بِأَبِي أَنْتَ وَأُمِّي، فَأَخْبَرْتُهُ الْخَبَرَ ‏.‏ قَالَ ‏:‏ ‏"‏ فَأَنْتِ السَّوَادُ الَّذِي رَأَيْتُ أَمَامِي ‏"‏ ‏.‏ قَالَتْ ‏:‏ نَعَمْ، فَلَهَزَنِي فِي صَدْرِي لَهْزَةً أَوْجَعَتْنِي، ثُمَّ قَالَ ‏:‏ ‏"‏ أَظَنَنْتِ أَنْ يَحِيفَ اللَّهُ عَلَيْكِ وَرَسُولُهُ ‏"‏ ‏.‏ قُلْتُ ‏:‏ مَهْمَا يَكْتُمُ النَّاسُ فَقَدْ عَلِمَهُ اللَّهُ ‏.‏ قَالَ ‏:‏ ‏"‏ فَإِنَّ جِبْرِيلَ أَتَانِي حِينَ رَأَيْتِ وَلَمْ يَدْخُلْ عَلَىَّ وَقَدْ وَضَعْتِ ثِيَابَكِ فَنَادَانِي، فَأَخْفَى مِنْكِ فَأَجَبْتُهُ فَأَخْفَيْتُهُ مِنْكِ، فَظَنَنْتُ أَنْ قَدْ رَقَدْتِ وَكَرِهْتُ أَنْ أُوقِظَكِ، وَخَشِيتُ أَنْ تَسْتَوْحِشِي، فَأَمَرَنِي أَنْ آتِيَ الْبَقِيعَ فَأَسْتَغْفِرَ لَهُمْ ‏"‏ ‏.‏ قُلْتُ ‏:‏ كَيْفَ أَقُولُ يَا رَسُولَ اللَّهِ قَالَ ‏:‏ ‏"‏ قُولِي السَّلاَمُ عَلَى أَهْلِ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ، يَرْحَمُ اللَّهُ الْمُسْتَقْدِمِينَ مِنَّا وَالْمُسْتَأْخِرِينَ، وَإِنَّا إِنْ شَاءَ اللَّهُ بِكُمْ لاَحِقُونَ ‏"‏ ‏.‏</text>

      </arabic>

      <english>

        <text>Muhammad bin Qais bin Makhramah said:</text>

        <text>"Aishah said: 'Shall I not tell you about me and about the Prophet?' We said: 'Yes.' She said: 'When it was my night when he was with me' - meaning the Prophet -'He came back (from 'Isha' prayer), put his sandals by his feet and spread the edge of his Izar on his bed. He stayed until he thought that I had gone to sleep. Then he put his sandals on slowly, picked up his cloak slowly, then opened the door slowly and went out slowly. I covered my head, put on my vie and tightened my waist wrapper, then I followed his steps until he came to Al-Baqi'. He raised his hands three times, and stood there for a long time, then he left and I left. He hastened and I also hastened; he ran and I also ran. He came (to the house) and I also came, but I got there first and entered, and as I lay down he came in. He said: "Tell me, or the Subtle, the All-Aware will tell me.' I said: 'O Messenger of Allah, may my father and mother be ransomed for you,' and I told him (the whole story). He said: 'So you were the black shape that I saw in front of me?' I said, 'Yes.' He gave me a nudge on the chest which I felt, then he said: 'Did you think that Allah and His Messenger would deal unjustly with you?' I said: 'Whatever the people conceal, Allah knows it.' He said: Jibril came to me when I saw you, but he did not enter upon me because you where not fully dressed. He called me but he concealed that from you, and I answered him, but I concealed that from you too. I thought that you had gone to sleep and I did not want to wake you up, and I was afraid that you would be frightened. He told me to go to Al-Baqi' and pray for forgiveness for them.' I said: 'What should I say, O Messenger of Allah?' He said: 'Say" Peace be upon the inhabitants of this place among the believers and Muslims. May Allah have mercy upon those who have gone on ahead of us and those who come later on, and we will join you, if Allah wills."'</text>

      </english>

      <verseReferences />

    </hadith>

 

Any idea why there is a difference? 

 

Thanks, 

 

Nick
